### ISSUE TITLE
BUG - Invalid yaml error is being thrown for valid yaml

### ISSUE THREAD

**Issue by kcpevey** [Quansight/conda-store#498]
I have the following yaml spec. There are two points in environment creation in conda-store that run a linter. This spec passes the linting that happens as you type into the yaml editor, but fails when you click create. The error is `Unable to parse. Invalid YAML`. However, if I paste it into a yaml linter online, it passes as valid yaml. 

There are two issues here - 
* the linter is throwing an error when it shouldn't (or its the wrong error)
* the linter needs to provide better error messaging so users can debug.

```
channels:
  - conda-forge
dependencies:
  - cdsdashboards-singleuser==0.6.2
  - holoviews
  - huggingface_hub
  - ipykernel
  - ipywidgets==7.7.1
  - matplotlib
  - nebari-dask==2023.1.1
  - numpy
  - pandas
  - panel
  - param
  - pyarrow
  - python
  - python-dotenv
  - python-graphviz
  - pytorch
  - questionary
  - requests
  - rich
  - s3fs
  - torchmetrics
  - torchvision
  - transformers
  - setuptools_scm
  - jsonschema
  - loguru
  - PyYAML
  - requests
  - toml
  - adversarial-robustness-toolbox==1.14.0
  - Pillow            
  - boto3              
  - botocore         
  - ffmpeg-python     
  - pydub       
  - tidecv    
  - opencv-python==4.5.5.62          
  - opencv-python-headless==4.5.5.62 
  - tensorboardx
  - scikit-learn<1.2.0 
  - scipy                 
  - numpy
  - pandas
  - matplotlib
  - torch>=2.0.0
  - torchaudio>=2.0.1
  - torchvision>=0.15.1
  - tf-models-official
  - tensorflow>=2.11.0
  - python-levenshtein
  - torchmetrics<0.8.0
  - sox
  - librosa
  - google-cloud-storage
  - transformers
  - pytorch-lightning<1.5.0
  - tensorflow-datasets>=4.9.0
  - protobuf
  - apache-beam>=2.22.0
  - mlflow
  - scipy>=1.7.3
  - pip:
    - hera
    - torcheval
    - xaitk-saliency>=0.7.0
```

**Comment by kcpevey** [comment]
Hmmm. After shutting down my server and copying the above into the conda-store ui, I can't reproduce the error. I messed around a little bit and have some notes:

* The error message at the top of the ui doesn't ALWAYS go away or change even after I fix the yaml. I tried two separate times and once it went away after I provided valid yaml and went on to build the env properly. Another time I fixed the yaml and the error message persisted. Something is wonky here. 
* Sometimes I do get more specific error messaging (i.e. I added quotes around this version number and this is the error: `1 validation error for CondaSpecification dependencies -> 58 Invalid conda package dependency specification apache-beam>="2.22.0" (type=value_error)`) 
* I haven't yet figured out I got the vague `Unable to parse. Invalid YAML` error.

**Comment by costrouc** [comment]
@kcpevey I've tested this out locally and it works for me on the old and new ui. I copied exactly what you put in the environment above. Can you still reproduce this issue?

**Comment by kcpevey** [comment]
I can't reproduce this issue. I suspect the cause is related to:

>The error message at the top of the ui doesn't ALWAYS go away or change even after I fix the yaml. I tried two separate times and once it went away after I provided valid yaml and went on to build the env properly. Another time I fixed the yaml and the error message persisted. Something is wonky here.

I think error messages are persisting even when the error has been fixed (which is confusing) and also the old error messages are preventing the screen update after clicking "Create". So the environment goes on to be built behind the scenes, but everything appears to the user as if you're still in an errored state.

**Comment by kcpevey** [comment]
See also the confusion around error messaging: https://github.com/Quansight/conda-store/issues/497
